apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: test_app
    tier: backend
    track: stable
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
